find_paper_task:
  description: >
    search for the latest papers about the given {topic},
    category is 'research paper',
    startPublishedDate is current year to date (2024)
    num_results=5
  expected_output: >
    get 5 papers from results from category of 'research paper',
    add title, paper_link, description for these five papers to the output,
    format the output as markdown.

research_task:
  description: >
    Rank the papers from {papers_list}, not just based on the publish date and total Citations,
    but also think about interesting and impact to podcast listener
    give them score
  expected_output: >
    choice one paper from the list,
    add title, paper_link, description to the output.

write_task:
  description: >
    Write podcast title and podcast description,
    based on the scraped content from the scrape_full_text_task or the original link,
    from the selected paper HTML link.
    make sure the catch for podcast viewer.
  expected_output: >
    provide title, description,  paper_link and prompt text for NLM in json format.
    add paper title, paper link, publish date and authors at the end of description.
    total English characters count should be less than 400.
    add a prompt text, less than 100, short intro to podcast host, how should they talk about this paper.
